import Head from 'next/head';
import Link from 'next/link';
import { blogPosts } from '../lib/data';


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Ramon's Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="p-5 mt-3 text-4xl">Welcome to Ramon's Next.JS tutorial!</h1>
      </main>
      <div className="p-5">
        {blogPosts.map((item) => (
          <div key={item.slug} className="p-5">
            <div>
              <Link href={`/blog/${item.slug}`}>
                <a className="underline text-2xl">{item.title}</a>
              </Link>
              </div>
            <div>{item.date.toString()}</div>
            <div>{item.content}</div>
          </div>
        ))}
      </div>
    </div>
  )
}
